services:
  payment-app:
    image: payment-app
    container_name: payment-app
    profiles:
      - prod
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - opensearch-node1
    env_file: .env
    environment:
      - PG_URL=user=postgres password=secret host=db port=5432 dbname=payments sslmode=disable
      - OPENSEARCH_URLS=http://opensearch-node1:9200
    ports:
      - "3000:3000"

  silvergate-mock:
    image: wiremock/wiremock:latest
    container_name: silvergate-mock
    profiles:
      - infra
    ports:
      - '8080:8080'
    volumes:
      - ./integration-test/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]

  db:
    image: postgres:13
    restart: always
    hostname: db
    profiles:
      - prod
      - infra
    networks:
      - backend
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data/

  opensearch-node1:
    image: opensearchproject/opensearch:3
    container_name: opensearch-node1
    profiles:
      - prod
      - infra
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true  # along with the memlock settings below, disables swapping
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536  # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600  # required for Performance Analyzer
    networks:
      - backend

  opensearch-node2:
    image: opensearchproject/opensearch:3
    container_name: opensearch-node2
    profiles:
      - prod
      - infra
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true    # dev only
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - backend

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3
    container_name: opensearch-dashboards
    profiles:
      - prod
      - infra
    ports:
      - 5601:5601
    expose:
      - '5601'
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"                                            # <<< add
    networks:
      - backend


volumes:
  db-data:
  opensearch-data1:
  opensearch-data2:

networks:
  backend:
  opensearch-net:
