services:
  just_pay:
    image: just_pay:dev
    container_name: just_pay
    networks:
      - backend
    depends_on:
      - db
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:

networks:
  backend: